### ISSUE TITLE
React-select cannot be defined as clearable

### ISSUE THREAD

**Issue by jluukka-ge** [OpusCapita/react-select#9]
__Expected behaviour__
Passing `isClearable` preperty with value `true` results in a react-select component with functionality for clearing the selected value (cross icon on the right edge of the input field).

__Current behaviour__
Passing `isClearable` property has no effect on the component. Functionality for clearing the selected value is not present.

**Comment by estambakio-sc** [comment]
@jluukka try to add `isClearable={true}` to the bottom input [on this page](https://opuscapita.github.io/react-select/branches/master/?currentComponentName=Creatable&showSidebar=true), the one which has `isMulti={true}` - indicator appears if something is selected.

This is the expected behavior I guess. Quote from `react-select` docs:

> The conditions under which the indicator will not be rendered when:
> 
> - When isClearable is false, or when isMulti is false, and isClearable is undefined
> - When the select is disabled
> - When the select has no value
> - When the select is loading

https://react-select.com/components#replaceable-components

**Comment by jluukka-ge** [comment]
I was fiddling with the components on the page you suggested. Clear-indicator is shown only with `isMulti={true}`. I also noticed that defining `isClearable={false}` with multiselect components has no effect either.

The code for the components pluck `isClearable`-property out of the parameter object in order to define the default value as `true`, but the property is not passed onward to `react-select`-component. 

PR to follow...
